name: EC2 Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts
    
    - name: SSH into EC2 and execute command
      run: |
       echo 'Hello from EC2 AWS_GitWorkflow_Deploy!' >> index.html
       scp -o StrictHostKeyChecking=no index.html ec2-user@${{ secrets.SSH_HOST }}:/var/www/html
